### PR TITLE
Feat : Result page

### PR DESCRIPTION
**Pull request by lomesshh**
Result page added where you can find answers for all questions
- you can see deploy preview here
- https://deploy-preview-6--quizzomania.netlify.app/components/result

### CODE REVIEW

**Review by ddivyansh18 — APPROVED** [review]
Looks good to merge !

**Review by Aman-Jain1996 — COMMENTED** [review]
Everything looks great but i saw somewhere you used px and rem both , ideally stick to 1 if possible

**Review by Aman-Jain1996 — APPROVED** [review]
Good to merge

**Review by Hnh013 — APPROVED** [review]
loved the color scheme and minimalist design , good to merge

**Comment by lomesshh** [comment]
> Everything looks great but i saw somewhere younused px and rem both , ideally stick to 1 if possible

I've done the changes as you suggested. Thank you !

**Pull request merged**
